# SERVER
APP_PORT=8080

# DATABASE (PostgreSQL URL format: postgres://user:password@host:port/dbname?sslmode=disable)
DATABASE_URL=postgres://postgres:postgres@localhost:5432/tedx_maps?sslmode=disable

# API KEYS
MAPS_API_KEY="YOUR_MAPS_API_KEY"