# Сборка Go backend
FROM golang:1.22 AS builder

WORKDIR /app
COPY . .

RUN go mod tidy && go build -o ./bin/tedx-maps ./cmd/server/main.go

# Финальный образ
FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/bin/tedx-maps /app/
COPY .env /app/

EXPOSE 8080

CMD ["./tedx-maps"]
